# Generated by Django 2.0.1 on 2018-01-16 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=200)),
                ('plan_date', models.DateField(blank=True, null=True)),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseManage.CategoryMoney')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseManage.Flat')),
            ],
        ),
    ]
