# Generated by Django 2.0.1 on 2018-01-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='flat_number',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneyreport',
            name='current_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
