# Generated by Django 2.0.1 on 2018-01-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseManage', '0002_auto_20180116_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyreport',
            name='money',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
